@extends('layout.layout')

@section('content')
<div class="jumbotron">
    <h1 class="display-4"><?= $framework ?> <small>Framework</small></h1>
    <p class="lead">Make it easy!</p>
    <hr class="my-4">
    <p class="lead">
        <a target="_blank" class="btn btn-primary btn-lg" href="http://www.dronephp.com" role="button">
            <span class="glyphicon glyphicon-share"></span> Go to Website
        </a>
    </p>
</div>

<p class="justify">
    This is a simple skeleton application for your project!.
</p>

<br /><br />
@endsection('content')

@section('footer')
Copyright 2019
@endsection('footer')